In [68]:
import pandas as pd

# VERSION = 'v1.1'
# VERSION = 'v1.2'
# data = pd.read_csv(f'sample_processed_internal_test_50_{VERSION}.csv')

VERSION = 'v6.4'
data = pd.read_csv(f'sample_processed_{VERSION}(외부병원).csv')


data.fillna(value='None', inplace=True)

labels = data.iloc[:,4:]

In [69]:
# pred = pd.read_excel('result_1224_chatgpt_InterTest_v1.2_.xlsx')
# pred = pd.read_excel('result_1016_chatgpt_InterTest_v1.1_GPT4.xlsx')
# pred = pd.read_excel('result_1016_chatgpt_InterTest_v1.1_o1-mini.xlsx')
# pred = pd.read_excel('result_1016_claude_InterTest_v1.1_.xlsx')
# pred = pd.read_excel('result_1016_gemini_InterTest_v1.1_.xlsx')


# pred = pd.read_excel('result_1016_external_chatgpt_v6.0_.xlsx')
pred = pd.read_excel('result_1016_external_chatgpt_v6.0_GPT4.xlsx')
# pred = pd.read_excel('result_1016_external_chatgpt_v6.0_o1-mini.xlsx')
# pred = pd.read_excel('result_1016_external_claude_v6.0_.xlsx')
# pred = pd.read_excel('result_1016_external_gemini_v6.0_.xlsx')


pred = pred.iloc[:, -9:-1]

# 모든 컬럼 이름에서 '.1' 제거
pred.columns = pred.columns.str.replace('.1', '')
pred = pred[labels.iloc[:,:-1].columns]
pred.loc[pred['CAD-RADS']=='4', 'CAD-RADS']='4A'
# pred.loc[pred['CAD-RADS']=='None', 'CAD-RADS']='0'

pred_noCoT = pred

C:\Users\User\AppData\Local\Temp\ipykernel_175912\332206010.py:18: FutureWarning: The default value of regex will change from True to False in a future version.
  pred.columns = pred.columns.str.replace('.1', '')


In [70]:
# pred = pd.read_excel('result_1224_chatgpt_InterTest_v1.2_CoT.xlsx')
# pred = pd.read_excel('result_1016_chatgpt_InterTest_v1.1_CoT_GPT4.xlsx')
# pred = pd.read_excel('result_1016_chatgpt_InterTest_v1.1_CoT_o1-mini.xlsx')
# pred = pd.read_excel('result_1016_claude_InterTest_v1.1_CoT.xlsx')
# pred = pd.read_excel('result_1016_gemini_InterTest_v1.1_CoT.xlsx')

# pred = pd.read_excel('result_1016_external_chatgpt_v6.0_CoT.xlsx')
pred = pd.read_excel('result_1016_external_chatgpt_v6.0_CoT_GPT4.xlsx')
# pred = pd.read_excel('result_1016_external_chatgpt_v6.0_CoT_o1-mini.xlsx')
# pred = pd.read_excel('result_1016_external_claude_v6.0_CoT.xlsx')
# pred = pd.read_excel('result_1016_external_gemini_v6.0_CoT.xlsx')

pred = pred.iloc[:, -9:-1]

# 모든 컬럼 이름에서 '.1' 제거
pred.columns = pred.columns.str.replace('.1', '')
pred = pred[labels.iloc[:,:-1].columns]
pred.loc[pred['CAD-RADS']=='4', 'CAD-RADS']='4A'
# pred.loc[pred['CAD-RADS']=='None', 'CAD-RADS']='0'

pred_CoT = pred

C:\Users\User\AppData\Local\Temp\ipykernel_175912\640930913.py:16: FutureWarning: The default value of regex will change from True to False in a future version.
  pred.columns = pred.columns.str.replace('.1', '')


In [71]:
from statsmodels.stats.contingency_tables import mcnemar
import numpy as np


for key in ['CAD-RADS', 'Plaque Burden', 'N']:
# for key in ['CAD-RADS', 'Plaque Burden', 'N', 'I', 'G', 'HRP', 'S', 'E']:
    
    if key == 'CAD-RADS':
        valid_index = labels['N']==0
    elif key == 'Plaque Burden':
        valid_index = (labels['S']==0) & (labels['CAC_available']==1)
        
    # 각 케이스별 정답 여부 (예시)
    # 1: 정답, 0: 오답
    # few_shot_results = np.tile(np.array(few_shot_pred[key] == labels[key]).astype(int), 4)
    # many_shot_results = np.tile(np.array(many_shot_pred[key] == labels[key]).astype(int), 4)  # 50개
    results_noCoT = np.array(pred_noCoT[valid_index][key] == labels[valid_index][key]).astype(int)  # 50개
    results_CoT = np.array(pred_CoT[valid_index][key] == labels[valid_index][key]).astype(int)  # 50개

    # Contingency table 생성
    table = np.zeros((2,2))
    for f, m in zip(results_noCoT, results_CoT):
        table[f][m] += 1
    print(table)

    # McNemar's test 수행
    result = mcnemar(table)
    p_value = result.pvalue
    print(key, p_value)

[[  9.  35.]
 [  3. 120.]]
CAD-RADS 6.677873898297548e-08
[[  4.  21.]
 [  0. 113.]]
Plaque Burden 9.5367431640625e-07
[[ 3. 39.]
 [ 1. 95.]]
N 7.457856554538012e-11


In [13]:
import pandas as pd

data.fillna(value='None', inplace=True)
labels = data.iloc[:,4:]

In [14]:
# pred = pd.read_excel('result_0828_external_gemini_v5.1.xlsx')
# pred = pred.iloc[:,-8:]

# pred = pd.read_excel('result_0829_external_gemini_v5.1_CoT_x_after_answer_x_none.xlsx')
# pred = pd.read_excel('result_0930_external_gemini_v6.0_CoT_edit.xlsx')
# pred = pred.iloc[:,-9:-1]

# pred = pd.read_excel('result_1014_external_gemini_v6.0_CoT_edit_certainty_UpperEnd.xlsx')
# pred = pd.read_excel('result_1016_external_gemini_v6.0_CoT_edit_certainty_UpperEnd.xlsx')
# certainty = pred[['certainty_cadrads', 'certainty_plaque']]
# pred = pred.iloc[:,-11:-3]

# pred = pd.read_excel('result_1016_external_gemini_v6.0_.xlsx')
pred = pd.read_excel('result_1016_external_gemini_v6.0_CoT.xlsx')
# pred = pd.read_excel('result_1028_external_gemini_v6.2_CoT_Shot100.xlsx')
# pred = pd.read_excel('result_1028_external_gemini_v6.2_CoT_Shot50.xlsx')
# pred = pd.read_excel('result_1028_external_gemini_v6.2_CoT_Shot20.xlsx')
# pred = pd.read_excel('result_1028_external_gemini_v6.2_CoT_Shot10.xlsx')
# pred = pd.read_excel('result_1028_external_gemini_v6.2_CoT_Shot3.xlsx')
# pred = pd.read_excel('result_1028_external_gemini_v6.2_CoT_Shot3_Seed421.xlsx')
# pred = pd.read_excel('result_1028_external_gemini_v6.2_CoT_Shot3_Seed422.xlsx')
# pred = pd.read_excel('result_1028_external_gemini_v6.2_CoT_Shot3_Seed423.xlsx')
# pred = pd.read_excel('result_1028_external_gemini_v6.2_CoT_Shot3_Seed424.xlsx')

# pred = pd.read_excel('result_1122_external_gemini_v6.3_flash.xlsx')
pred = pred.iloc[:, -9:-1]

# 모든 컬럼 이름에서 '.1' 제거
pred.columns = pred.columns.str.replace('.1', '')
pred = pred[labels.iloc[:,:-1].columns]

few_shot_pred = pred

C:\Users\User\AppData\Local\Temp\ipykernel_219000\2322398899.py:29: FutureWarning: The default value of regex will change from True to False in a future version.
  pred.columns = pred.columns.str.replace('.1', '')


In [15]:
paths = [
    'External_repeated/results/result_1028_gemini_External_v6.2_CoT_Shot100_Seed42.xlsx',
    'External_repeated/results/result_1028_gemini_External_v6.2_CoT_Shot100_Seed421_20241031_044331.xlsx',
    'External_repeated/results/result_1028_gemini_External_v6.2_CoT_Shot100_Seed422_20241031_054446.xlsx',
    'External_repeated/results/result_1028_gemini_External_v6.2_CoT_Shot100_Seed423_20241031_063913.xlsx',
    'External_repeated/results/result_1028_gemini_External_v6.2_CoT_Shot100_Seed424_20241031_072853.xlsx',
    'External_repeated/results/result_1028_gemini_External_v6.2_CoT_Shot100_Seed425_20241031_081206.xlsx',
    'External_repeated/results/result_1028_gemini_External_v6.2_CoT_Shot100_Seed426_20241031_085531.xlsx',
    'External_repeated/results/result_1028_gemini_External_v6.2_CoT_Shot100_Seed427_20241031_093724.xlsx',
    'External_repeated/results/result_1028_gemini_External_v6.2_CoT_Shot100_Seed428_20241031_102058.xlsx',
    'External_repeated/results/result_1028_gemini_External_v6.2_CoT_Shot100_Seed429_20241031_110715.xlsx',
    ]

In [16]:
from sklearn.metrics import accuracy_score
import numpy as np

# 각 실험결과의 성능을 저장할 딕셔너리 
performance = {}

# 각 실험 결과에 대해 성능 계산
for path in paths:
   pred = pd.read_excel(path)
   pred = pred.iloc[:, -9:-1]
   pred.columns = pred.columns.str.replace('.1', '')
   pred = pred[labels.iloc[:,:-1].columns]
   pred.loc[pred['CAD-RADS']=='4', 'CAD-RADS']='4A'
   
   # CAD-RADS accuracy 계산
   cad_valid_index = labels['N']==0
   cad_acc = accuracy_score(labels[cad_valid_index]['CAD-RADS'], 
                          pred[cad_valid_index]['CAD-RADS'])
   
   # Plaque Burden accuracy 계산
   plaque_valid_index = (labels['S']==0) & (labels['CAC_available']==1)
   plaque_acc = accuracy_score(labels[plaque_valid_index]['Plaque Burden'],
                             pred[plaque_valid_index]['Plaque Burden'])
   
   # Modifiers accuracy 계산
   modifier_columns = ['N', 'I', 'HRP', 'S', 'E', 'G']
   modifier_accs = []
   for modifier in modifier_columns:
       modifier_acc = accuracy_score(labels[modifier], pred[modifier])
       modifier_accs.append(modifier_acc)
   avg_modifier_acc = np.mean(modifier_accs)
   
   performance[path] = {
       'cad_acc': cad_acc,
       'plaque_acc': plaque_acc,
       'modifier_acc': avg_modifier_acc,
       'predictions': pred
   }

# 최악의 성능을 보인 실험 찾기
worst_cad = min(performance.items(), key=lambda x: x[1]['cad_acc'])
worst_plaque = min(performance.items(), key=lambda x: x[1]['plaque_acc'])
worst_modifier = min(performance.items(), key=lambda x: x[1]['modifier_acc'])

# 결과를 하나의 DataFrame으로 결합
final_predictions = pd.DataFrame(index=labels.index)

# 각각 최악의 성능을 보인 실험의 예측값 가져오기
final_predictions['CAD-RADS'] = performance[worst_cad[0]]['predictions']['CAD-RADS']
final_predictions['Plaque Burden'] = performance[worst_plaque[0]]['predictions']['Plaque Burden']
for modifier in ['N', 'I', 'HRP', 'S', 'E', 'G']:
   final_predictions[modifier] = performance[worst_modifier[0]]['predictions'][modifier]

# 어떤 실험이 선택되었는지 출력
print(f"Worst CAD-RADS performance (Accuracy={worst_cad[1]['cad_acc']:.3f}): {worst_cad[0]}")
print(f"Worst Plaque Burden performance (Accuracy={worst_plaque[1]['plaque_acc']:.3f}): {worst_plaque[0]}")
print(f"Worst Modifiers performance (Averaged Accuracy={worst_modifier[1]['modifier_acc']:.3f}): {worst_modifier[0]}")

print("\nFinal predictions shape:", final_predictions.shape)
many_shot_pred = final_predictions

C:\Users\User\AppData\Local\Temp\ipykernel_219000\2364300205.py:11: FutureWarning: The default value of regex will change from True to False in a future version.
  pred.columns = pred.columns.str.replace('.1', '')
C:\Users\User\AppData\Local\Temp\ipykernel_219000\2364300205.py:11: FutureWarning: The default value of regex will change from True to False in a future version.
  pred.columns = pred.columns.str.replace('.1', '')
C:\Users\User\AppData\Local\Temp\ipykernel_219000\2364300205.py:11: FutureWarning: The default value of regex will change from True to False in a future version.
  pred.columns = pred.columns.str.replace('.1', '')
C:\Users\User\AppData\Local\Temp\ipykernel_219000\2364300205.py:11: FutureWarning: The default value of regex will change from True to False in a future version.
  pred.columns = pred.columns.str.replace('.1', '')
C:\Users\User\AppData\Local\Temp\ipykernel_219000\2364300205.py:11: FutureWarning: The default value of regex will change from True to False in 

Worst CAD-RADS performance (Accuracy=0.868): External_repeated/results/result_1028_gemini_External_v6.2_CoT_Shot100_Seed421_20241031_044331.xlsx
Worst Plaque Burden performance (Accuracy=0.986): External_repeated/results/result_1028_gemini_External_v6.2_CoT_Shot100_Seed426_20241031_085531.xlsx
Worst Modifiers performance (Averaged Accuracy=0.993): External_repeated/results/result_1028_gemini_External_v6.2_CoT_Shot100_Seed422_20241031_054446.xlsx

Final predictions shape: (169, 8)


C:\Users\User\AppData\Local\Temp\ipykernel_219000\2364300205.py:11: FutureWarning: The default value of regex will change from True to False in a future version.
  pred.columns = pred.columns.str.replace('.1', '')
C:\Users\User\AppData\Local\Temp\ipykernel_219000\2364300205.py:11: FutureWarning: The default value of regex will change from True to False in a future version.
  pred.columns = pred.columns.str.replace('.1', '')


In [17]:
from statsmodels.stats.contingency_tables import mcnemar
import numpy as np


for key in ['CAD-RADS', 'Plaque Burden']:
    
    if key == 'CAD-RADS':
        valid_index = labels['N']==0
    elif key == 'Plaque Burden':
        valid_index = (labels['S']==0) & (labels['CAC_available']==1)
        
    # 각 케이스별 정답 여부 (예시)
    # 1: 정답, 0: 오답
    # few_shot_results = np.tile(np.array(few_shot_pred[key] == labels[key]).astype(int), 4)
    # many_shot_results = np.tile(np.array(many_shot_pred[key] == labels[key]).astype(int), 4)  # 50개
    few_shot_results = np.array(few_shot_pred[valid_index][key] == labels[valid_index][key]).astype(int)  # 50개
    many_shot_results = np.array(many_shot_pred[valid_index][key] == labels[valid_index][key]).astype(int)  # 50개

    # Contingency table 생성
    table = np.zeros((2,2))
    for f, m in zip(few_shot_results, many_shot_results):
        table[f][m] += 1
    print(table)

    # McNemar's test 수행
    result = mcnemar(table)
    p_value = result.pvalue
    print(key, p_value)

[[  9.  15.]
 [ 13. 130.]]
CAD-RADS 0.8505540192127228
[[  1.   9.]
 [  1. 127.]]
Plaque Burden 0.021484375


In [18]:
print('worst cads acc', performance[worst_cad[0]]['cad_acc'])
print('worst plaque acc', performance[worst_plaque[0]]['plaque_acc'])
print('worst plaque acc', performance[worst_modifier[0]]['modifier_acc'])

worst cads acc 0.8682634730538922
worst plaque acc 0.9855072463768116
worst plaque acc 0.9930966469428008
