In [1]:
import pandas as pd

# VERSION = 'v1.1'
VERSION = 'v1.2'
data = pd.read_csv(f'sample_processed_internal_test_50_{VERSION}.csv')

# VERSION = 'v6.4'
# data = pd.read_csv(f'sample_processed_{VERSION}(외부병원).csv')


data.fillna(value='None', inplace=True)

labels = data.iloc[:,4:]

In [35]:
# pred = pd.read_excel('result_1224_chatgpt_InterTest_v1.2_.xlsx')
# pred = pd.read_excel('result_1016_chatgpt_InterTest_v1.1_GPT4.xlsx')
# pred = pd.read_excel('result_1016_chatgpt_InterTest_v1.1_o1-mini.xlsx')
# pred = pd.read_excel('result_1016_claude_InterTest_v1.1_.xlsx')
# pred = pd.read_excel('result_1016_gemini_InterTest_v1.1_.xlsx')


# pred = pd.read_excel('result_1016_external_chatgpt_v6.0_.xlsx')
# pred = pd.read_excel('result_1016_external_chatgpt_v6.0_GPT4.xlsx')
# pred = pd.read_excel('result_1016_external_chatgpt_v6.0_o1-mini.xlsx')
# pred = pd.read_excel('result_1016_external_claude_v6.0_.xlsx')
# pred = pd.read_excel('result_1016_external_gemini_v6.0_.xlsx')

# pred = pd.read_excel('result_0211_deepseek_InterTest_v1.2_.xlsx')
# pred = pd.read_excel('result_0213_external_deepseek_v6.4_.xlsx')


# pred = pd.read_excel('result_0526_chatgpt_InterTest_v1.2_zero-shot.xlsx')
# pred = pd.read_excel('result_0526_chatgpt_InterTest_v1.2_zero-shot_GPT4.xlsx')
# pred = pd.read_excel('result_0526_chatgpt_InterTest_v1.2_zero-shot_o1-mini.xlsx')
# pred = pd.read_excel('result_0526_claude_InterTest_v1.2_zero-shot.xlsx')
# pred = pd.read_excel('result_0526_gemini_InterTest_v1.2_zero-shot.xlsx')
pred = pd.read_excel('result_0526_deepseek_InterTest_v1.2_zero-shot.xlsx')


# pred = pd.read_excel('result_0526_external_chatgpt_v6.4_zero-shot.xlsx')
# pred = pd.read_excel('result_0526_external_chatgpt_v6.4_zero-shot_gpt4.xlsx')
# pred = pd.read_excel('result_0526_external_chatgpt_v6.4_zero-shot_o1-mini.xlsx')
# pred = pd.read_excel('result_0526_external_claude_v6.4_zero-shot.xlsx')
# pred = pd.read_excel('result_0526_external_gemini_v6.4_zero-shot.xlsx')
# pred = pd.read_excel('result_0526_external_deepseek_v6.4_zero-shot.xlsx')

pred = pred.iloc[:, -9:-1]

# 모든 컬럼 이름에서 '.1' 제거
pred.columns = pred.columns.str.replace('.1', '')
pred = pred[labels.iloc[:,:-1].columns]
pred.loc[pred['CAD-RADS']=='4', 'CAD-RADS']='4A'
# pred.loc[pred['CAD-RADS']=='None', 'CAD-RADS']='0'

pred_noCoT = pred

C:\Users\User\AppData\Local\Temp\ipykernel_341620\2148445681.py:36: FutureWarning: The default value of regex will change from True to False in a future version.
  pred.columns = pred.columns.str.replace('.1', '')


In [36]:
# pred = pd.read_excel('result_1224_chatgpt_InterTest_v1.2_CoT.xlsx')
# pred = pd.read_excel('result_1016_chatgpt_InterTest_v1.1_CoT_GPT4.xlsx')
# pred = pd.read_excel('result_1016_chatgpt_InterTest_v1.1_CoT_o1-mini.xlsx')
# pred = pd.read_excel('result_1016_claude_InterTest_v1.1_CoT.xlsx')
# pred = pd.read_excel('result_1016_gemini_InterTest_v1.1_CoT.xlsx')

# pred = pd.read_excel('result_1016_external_chatgpt_v6.0_CoT.xlsx')
# pred = pd.read_excel('result_1016_external_chatgpt_v6.0_CoT_GPT4.xlsx')
# pred = pd.read_excel('result_1016_external_chatgpt_v6.0_CoT_o1-mini.xlsx')
# pred = pd.read_excel('result_1016_external_claude_v6.0_CoT.xlsx')
# pred = pd.read_excel('result_1016_external_gemini_v6.0_CoT.xlsx')

# pred = pd.read_excel('result_0211_deepseek_InterTest_v1.2_CoT.xlsx')
# pred = pd.read_excel('result_0213_external_deepseek_v6.4_CoT.xlsx')


# pred = pd.read_excel('result_0526_chatgpt_InterTest_v1.2_zero-shot_CoT.xlsx')
# pred = pd.read_excel('result_0526_chatgpt_InterTest_v1.2_zero-shot_GPT4_CoT.xlsx')
# pred = pd.read_excel('result_0526_chatgpt_InterTest_v1.2_zero-shot_o1-mini_CoT_again.xlsx')
# pred = pd.read_excel('result_0526_claude_InterTest_v1.2_zero-shot_CoT.xlsx')
# pred = pd.read_excel('result_0526_gemini_InterTest_v1.2_zero-shot_CoT.xlsx')
pred = pd.read_excel('result_0526_deepseek_InterTest_v1.2_zero-shot_CoT.xlsx')

# pred = pd.read_excel('result_0526_external_chatgpt_v6.4_zero-shot_CoT.xlsx')
# pred = pd.read_excel('result_0526_external_chatgpt_v6.4_zero-shot_gpt4_CoT.xlsx')
# pred = pd.read_excel('result_0526_external_chatgpt_v6.4_zero-shot_o1-mini_CoT.xlsx')
# pred = pd.read_excel('result_0526_external_claude_v6.4_zero-shot_CoT.xlsx')
# pred = pd.read_excel('result_0526_external_gemini_v6.4_zero-shot_CoT.xlsx')
# pred = pd.read_excel('result_0526_external_deepseek_v6.4_zero-shot_CoT.xlsx')



pred = pred.iloc[:, -9:-1]

# 모든 컬럼 이름에서 '.1' 제거
pred.columns = pred.columns.str.replace('.1', '')
pred = pred[labels.iloc[:,:-1].columns]
pred.loc[pred['CAD-RADS']=='4', 'CAD-RADS']='4A'
# pred.loc[pred['CAD-RADS']=='None', 'CAD-RADS']='0'

pred_CoT = pred

C:\Users\User\AppData\Local\Temp\ipykernel_341620\2835699597.py:36: FutureWarning: The default value of regex will change from True to False in a future version.
  pred.columns = pred.columns.str.replace('.1', '')


In [37]:
from statsmodels.stats.contingency_tables import mcnemar
import numpy as np


# for key in ['CAD-RADS', 'Plaque Burden', 'N']:
for key in ['CAD-RADS', 'Plaque Burden', 'N', 'I', 'G', 'HRP', 'S', 'E']:
    
    if key == 'CAD-RADS':
        valid_index = labels['N']==0
    elif key == 'Plaque Burden':
        valid_index = (labels['S']==0) & (labels['CAC_available']==1)
        
    # 각 케이스별 정답 여부 (예시)
    # 1: 정답, 0: 오답
    # few_shot_results = np.tile(np.array(few_shot_pred[key] == labels[key]).astype(int), 4)
    # many_shot_results = np.tile(np.array(many_shot_pred[key] == labels[key]).astype(int), 4)  # 50개
    results_noCoT = np.array(pred_noCoT[valid_index][key] == labels[valid_index][key]).astype(int)  # 50개
    results_CoT = np.array(pred_CoT[valid_index][key] == labels[valid_index][key]).astype(int)  # 50개

    # Contingency table 생성
    table = np.zeros((2,2))
    for f, m in zip(results_noCoT, results_CoT):
        table[f][m] += 1
    print(table)

    # McNemar's test 수행
    result = mcnemar(table)
    p_value = result.pvalue
    print(key, p_value)

[[ 4.  3.]
 [ 1. 41.]]
CAD-RADS 0.625
[[ 2.  2.]
 [ 2. 37.]]
Plaque Burden 1.0
[[ 1.  1.]
 [ 2. 39.]]
N 1.0
[[ 0.  0.]
 [ 0. 43.]]
I 1.0
[[ 0.  0.]
 [ 0. 43.]]
G 1.0
[[ 0.  1.]
 [ 0. 42.]]
HRP 1.0
[[ 0.  1.]
 [ 0. 42.]]
S 1.0
[[ 0.  1.]
 [ 0. 42.]]
E 1.0


In [5]:
for key in ['CAD-RADS', 'Plaque Burden', 'N', 'I', 'G', 'HRP', 'S', 'E']:
    
    if key == 'CAD-RADS':
        valid_index = labels['N']==0
    elif key == 'Plaque Burden':
        valid_index = (labels['S']==0) & (labels['CAC_available']==1)

    print(key)
    print(valid_index.sum())

CAD-RADS
49
Plaque Burden
43
N
43
I
43
G
43
HRP
43
S
43
E
43
